# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='子模块名称')),
                ('pillar', jsonfield.fields.JSONField(default={})),
                ('env_tag', models.CharField(default='', max_length=128, verbose_name='环境标签')),
                ('is_lock', models.IntegerField(choices=[(0, '否'), (1, '是')], default='0', verbose_name='是否锁定')),
                ('include_instances', models.ManyToManyField(related_name='_instance_include_instances_+', to='geniusalt.Instance')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256, unique=True, verbose_name='模块名称')),
                ('pillar_required', jsonfield.fields.JSONField(default=[])),
                ('pillar_optional', jsonfield.fields.JSONField(default=[])),
                ('lock_count', models.IntegerField(default='0', verbose_name='锁定计数')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256, unique=True, verbose_name='节点名称')),
                ('environment', models.CharField(default='', max_length=128, verbose_name='所属环境')),
                ('instances', models.ManyToManyField(to='geniusalt.Instance')),
            ],
        ),
        migrations.AddField(
            model_name='instance',
            name='module_belong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='geniusalt.Module'),
        ),
    ]
