# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geniusalt', '0002_auto_20180124_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=8, unique=True, verbose_name='用户名称')),
                ('token', models.CharField(default='', max_length=64, unique=True, verbose_name='用户TOKEN')),
                ('sign_date', models.DateTimeField(auto_now_add=True, verbose_name='注册日期')),
                ('expired_time', models.IntegerField(default=86400, verbose_name='有效期限')),
            ],
        ),
    ]
