# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-02-02 15:57
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('geniusalt', '0004_auto_20180201_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instance',
            name='included_instances',
        ),
        migrations.AddField(
            model_name='instance',
            name='included_instances',
            field=jsonfield.fields.JSONField(default=[]),
        ),
    ]
