# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-02-02 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geniusalt', '0005_auto_20180202_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncludeRelationship',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='instance',
            name='included_instances',
        ),
        migrations.AddField(
            model_name='includerelationship',
            name='r_included',
            field=models.ManyToManyField(to='geniusalt.Instance'),
        ),
        migrations.AddField(
            model_name='includerelationship',
            name='r_instance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='r_instance', to='geniusalt.Instance'),
        ),
    ]
