# Generated by Django 2.0.7 on 2018-07-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geniusalt', '0006_auto_20180202_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(default='', max_length=128, unique=True, verbose_name='模块名称'),
        ),
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(default='', max_length=128, unique=True, verbose_name='节点名称'),
        ),
    ]
