# Generated by Django 2.0.7 on 2018-08-14 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geniusalt', '0008_auto_20180802_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='included_instances',
            field=models.ManyToManyField(to='geniusalt.Instance'),
        ),
    ]
